# version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: mynewapp-backend
#     ports:
#       - "5000:5000"
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_USER: postgres
#       DB_PASSWORD: password
#       DB_NAME: myapp
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     container_name: mynewapp-db
#     restart: always
#     environment:
#       POSTGRES_DB: myapp
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mynewapp-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    # ⚠️ Removed environment section (you’re not using env vars in Go)

  db:
    image: postgres:13
    container_name: mynewapp-db
    restart: always
    environment:
      POSTGRES_DB: postgres           # ✅ matches dbName := "postgres"
      POSTGRES_USER: postgres         # ✅ matches user := "postgres"
      POSTGRES_PASSWORD: nm00         # ✅ matches password := "nm00"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
